# Generated by Django 5.2.2 on 2025-06-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
            },
        ),
    ]
